name: theta_chat
description: "Thera Chat"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ui theme
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2

  # ui
  persistent_bottom_nav_bar: ^5.0.2

  # connection
  internet_connection_checker: ^1.0.0+1

  # service locator
  get_it: ^7.6.4

  #network
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1

  #store
  flutter_secure_storage: ^7.0.1
  shared_preferences: ^2.2.2

  #state manager
  equatable: ^2.0.5
  flutter_riverpod: ^2.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/